"""
Tests for the run-manifest wiring in llm-sum/run_phase3.py::cmd_evaluate().

These are wiring-level tests: they exercise the actual CLI entrypoint (via
the real argparse parser) in PHASE3_MODE=test (mock judge, $0, no live API
calls) and assert a run_manifest_*.json appears with the expected shape.

In plain English: this file is a set of automated checks that make sure the
command-line tool in llm-sum/run_phase3.py behaves correctly WITHOUT ever
calling a real, paid AI provider. Every test below runs entirely in
"--mode test", which is a safe mock mode built into the project: whenever a
test "calls" OpenAI/Anthropic/Gemini, it actually gets a fake, instant,
free response instead of a real one. That's what lets these tests run safely
and automatically (including here, via Claude) without risking any cost.
Each test function (the ones named `test_...`) sets up some fake data,
runs a piece of run_phase3.py's logic, and then checks ("asserts") that the
result looks the way it should.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest


# In plain English: a "fixture" (the @pytest.fixture decorator below) is
# pytest's way of saying "before each test runs, set up this piece of shared
# scaffolding for it." `autouse=True` means every single test in this file
# gets this fixture automatically, without having to ask for it by name.
@pytest.fixture(autouse=True)
def _default_judge_panel(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin the default judge set to the full 3-judge panel.

    These are wiring tests; the default is now the openai,anthropic,gemini
    panel, so we pin it explicitly for determinism (rather than depending on the
    ambient .env JUDGE_MODELS / JURY_PRESET) while still exercising the real
    3-judge default. Tests that opt into a different set via --judges/--jury
    still override this (CLI wins in resolve_judges).

    In plain English: forces every test to use the same 3-judge lineup
    (OpenAI, Anthropic, Gemini) as the "default" judges, regardless of
    whatever is currently written in the real .env file on this machine.
    `monkeypatch` is a pytest tool that temporarily changes a setting just
    for the duration of one test, then automatically puts it back afterward
    — so these tests can't accidentally leave a changed setting behind.
    """
    import evaluator

    monkeypatch.setattr(evaluator, "JUDGE_MODELS", list(evaluator.JURY_PANEL))
    monkeypatch.delenv("JURY_PRESET", raising=False)


def _write_fake_summaries(summaries_path: Path, processed_dir: Path, dois: list[str]) -> None:
    """In plain English: writes fake/pretend summary data to disk that looks
    exactly like real output from `summarize`, but was never generated by
    an AI. This gives the tests below something realistic to evaluate/judge
    without making any real API call."""
    from file_paths import doi_to_slug

    processed_dir.mkdir(parents=True, exist_ok=True)
    with open(summaries_path, "w", encoding="utf-8") as f:
        for doi in dois:
            slug = doi_to_slug(doi)
            (processed_dir / f"{slug}.jsonl").write_text(
                json.dumps({"doi": doi, "slug": slug, "text": "Reference body. " * 30}) + "\n",
                encoding="utf-8",
            )
            f.write(json.dumps({
                "doi": doi,
                "custom_id": slug,
                "models": {
                    "openai": {
                        "status": "success",
                        "summary": f"summary for {doi}",
                        "model_version": "gpt-5.4-test",
                        "input_tokens": 100, "output_tokens": 50,
                    }
                },
            }) + "\n")


@pytest.fixture()
def _wired_paths(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Redirect every module-level path constant this wiring touches into tmp_path.

    In plain English: this fixture makes sure that when a test runs, ALL file
    reading/writing happens inside a scratch/throwaway folder (`tmp_path`,
    created fresh by pytest for each test and deleted afterward) instead of
    the project's real data/ folder. That's what guarantees running these
    tests can never overwrite or corrupt real summaries.jsonl or
    evaluations.jsonl. Unlike the fixture above, this one isn't automatic —
    only tests that list `_wired_paths` as a parameter get it.
    """
    import evaluator
    import eval_report
    import eval_instances
    import prepare_texts
    import run_phase3
    import summarize_all_ingest

    summaries_path = tmp_path / "summaries.jsonl"
    evaluations_path = tmp_path / "evaluations.jsonl"
    processed_dir = tmp_path / "processed"

    monkeypatch.setattr(evaluator, "SUMMARIES_PATH", summaries_path)
    # The summarize-all input modes now judge the prose summary_text out of
    # summaries.jsonl rather than the bulleted .txt body, so this path has to
    # be redirected too or those tests would read the real project file.
    monkeypatch.setattr(summarize_all_ingest, "SUMMARIES_PATH", summaries_path)
    # cmd_evaluate's journal-stratified sampling branch (single/dev/batch,
    # anything other than --mode test) reads run_phase3's OWN module-level
    # SUMMARIES_PATH/MANIFEST_PATH directly — a separate pair of constants
    # from evaluator's, not a re-export — so patching only evaluator's above
    # leaves this branch reading the real project data/summaries.jsonl and
    # data/manifest.jsonl. --mode test never hits this branch (no journal
    # stratification there), which is why this gap went unnoticed until a
    # test exercised single/dev/batch's real sampling path.
    monkeypatch.setattr(run_phase3, "SUMMARIES_PATH", summaries_path)
    monkeypatch.setattr(run_phase3, "MANIFEST_PATH", tmp_path / "manifest.jsonl")
    monkeypatch.setattr(evaluator, "EVALUATIONS_PATH", evaluations_path)
    monkeypatch.setattr(evaluator, "PROCESSED_DIR", processed_dir)
    monkeypatch.setattr(prepare_texts, "PROCESSED_DIR", processed_dir)
    monkeypatch.setattr(eval_report, "EVALUATIONS_PATH", evaluations_path)
    monkeypatch.setattr(run_phase3, "RUN_MANIFEST_DIR", tmp_path)
    # write_dev_eval_jsonl_outputs/write_dev_detail_eval_outputs load the real
    # manifest by default when no manifest_index is passed in; point that at
    # tmp (nonexistent) paths too so tests never touch data/manifest.jsonl.
    monkeypatch.setattr(eval_instances, "MANIFEST_PATH", tmp_path / "manifest.jsonl")
    monkeypatch.setattr(eval_instances, "MANUAL_MANIFEST_PATH", tmp_path / "manual_manifest.jsonl")
    # _cmd_evaluate_from_txt_folder reads run_phase3.SUMMARIES_TXT_DIR /
    # DEV_TESTS_SUMMARIES_TXT_DIR -- real, unpatched project folders -- when
    # input_mode resolves to "regular"/"dev". That only happens if a test's
    # ambient EVAL_INPUT_MODE (from the developer's own .env) isn't "jsonl";
    # pin it here so this fixture's hermeticity guarantee holds regardless of
    # the machine it runs on. Any test that wants a different input mode
    # passes --input-mode explicitly, which always wins over this.
    monkeypatch.setenv("EVAL_INPUT_MODE", "jsonl")

    return {
        "summaries_path": summaries_path,
        "evaluations_path": evaluations_path,
        "processed_dir": processed_dir,
        "manifest_dir": tmp_path,
    }


def _run_evaluate(argv: list[str]):
    """In plain English: pretends to type `python llm-sum/run_phase3.py
    evaluate ...` by feeding a list of strings (argv, e.g.
    ["evaluate", "--mode", "test"]) through the SAME argparse parser
    run_phase3.py itself builds, then calls cmd_evaluate exactly the way the
    real CLI would. This is the standard way these tests drive the real code
    path instead of a simplified stand-in."""
    import run_phase3

    parser = run_phase3.build_parser()
    args = parser.parse_args(argv)
    return run_phase3.cmd_evaluate(args)


def _find_manifest(manifest_dir: Path) -> Path:
    """In plain English: looks in the scratch folder for the one
    run_manifest_*.json file that `evaluate` should have written, and fails
    the test immediately (with a clear message) if there isn't exactly one."""
    manifests = sorted(manifest_dir.glob("run_manifest_*.json"))
    assert len(manifests) == 1, f"expected exactly one manifest, found {manifests}"
    return manifests[0]


# In plain English: checks that running `evaluate --mode test` on two fake
# papers finishes successfully and writes a run-manifest record file that
# correctly lists both papers, the full 3-judge panel, and a "completed"
# status — the audit-trail record the real safety/reproducibility system
# depends on.
def test_evaluate_test_mode_writes_completed_run_manifest(_wired_paths) -> None:
    dois = ["10.9999/manifest.0001", "10.9999/manifest.0002"]
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], dois)

    result = _run_evaluate(["evaluate", "--mode", "test"])

    assert result == 0
    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))

    from evaluator import JURY_PANEL

    assert data["status"] == "completed"
    assert data["finished_utc"] is not None
    assert sorted(data["selected_instance_ids"]) == sorted(dois)
    # Default is now the full 3-judge panel.
    assert data["judges"] == JURY_PANEL
    assert all(j in data["model_ids"] for j in JURY_PANEL)
    # DRY_RUN mock mode returns "<model_id>-DRYRUN" as the judge's observed
    # version — this proves resolved_model_versions reads the real judge
    # response, not just echoing the configured model_ids. Every panel judge
    # should carry that mock marker.
    for judge in JURY_PANEL:
        assert data["resolved_model_versions"].get(judge, "").endswith("-DRYRUN")
    assert data["evaluation_config"]["mode"] == "test"
    taxonomy = data["evaluation_config"]["taxonomy"]
    assert taxonomy["taxonomy_id"] == "vet_taxonomy_v1"
    assert taxonomy["task_key"] == "veterinary_summary_quality"


# ---------------------------------------------------------------------------
# evaluate --mode batch: full-corpus default + batch/real-time judge split
# ---------------------------------------------------------------------------

def _write_fake_summaries_with_journals(
    summaries_path: Path, processed_dir: Path, dois_by_journal: dict[str, list[str]],
) -> None:
    """Like _write_fake_summaries, but with an explicit "journal" field per
    row (read directly by _load_summaries_by_journal before it ever falls
    back to manifest.jsonl), across multiple journals with multiple papers
    each — needed to tell "1 per journal" apart from "every paper"."""
    from file_paths import doi_to_slug

    processed_dir.mkdir(parents=True, exist_ok=True)
    with open(summaries_path, "w", encoding="utf-8") as f:
        for journal, dois in dois_by_journal.items():
            for doi in dois:
                slug = doi_to_slug(doi)
                (processed_dir / f"{slug}.jsonl").write_text(
                    json.dumps({"doi": doi, "slug": slug, "text": "Reference body. " * 30}) + "\n",
                    encoding="utf-8",
                )
                f.write(json.dumps({
                    "doi": doi,
                    "custom_id": slug,
                    "journal": journal,
                    "models": {
                        p: {"status": "success", "summary": f"{p} summary for {doi}"}
                        for p in ("openai", "anthropic", "gemini")
                    },
                }) + "\n")


# In plain English: two bugs, one test. (1) `evaluate --mode batch` with no
# --limit used to sample only 1 paper PER JOURNAL (a `None or 1` bug in the
# per-journal quota formula) instead of the whole corpus — this asserts every
# journal-mapped paper is included. (2) `evaluate --mode batch` never
# actually submitted a batch job for any judge — this asserts OpenAI/
# Anthropic (batch-enabled by default) go through run_batch_evaluation while
# Gemini (real-time by default) goes through run_evaluation, mirroring the
# summarize-side split exactly, and that both legs see the same full-corpus
# doi_filter.
def test_evaluate_batch_mode_dispatches_split_judges_over_full_corpus(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    import batch_utils
    import evaluator

    dois_by_journal = {
        "jvim": ["10.9999/j1.1", "10.9999/j1.2", "10.9999/j1.3"],
        "javma": ["10.9999/j2.1", "10.9999/j2.2"],
    }
    _write_fake_summaries_with_journals(
        _wired_paths["summaries_path"], _wired_paths["processed_dir"], dois_by_journal,
    )

    batch_calls: list[dict] = []
    realtime_calls: list[dict] = []

    def _fake_run_batch_evaluation(*, judges, doi_filter, **_kwargs):
        batch_calls.append({"judges": sorted(judges), "doi_filter": set(doi_filter)})
        return {"submitted": []}

    def _fake_run_evaluation(*, judges, doi_filter, **_kwargs):
        realtime_calls.append({"judges": sorted(judges), "doi_filter": set(doi_filter)})
        return {"success": 0, "failed": 0}

    monkeypatch.setattr(batch_utils, "run_batch_evaluation", _fake_run_batch_evaluation)
    monkeypatch.setattr(evaluator, "run_evaluation", _fake_run_evaluation)

    ret = _run_evaluate(["evaluate", "--mode", "batch", "--force"])

    assert ret == 0
    all_dois = {doi for dois in dois_by_journal.values() for doi in dois}

    assert len(batch_calls) == 1
    assert batch_calls[0]["judges"] == ["anthropic", "openai"]
    assert batch_calls[0]["doi_filter"] == all_dois, (
        "batch mode with no --limit must judge every journal-mapped summary, "
        "not just 1 per journal"
    )

    assert len(realtime_calls) == 1
    assert realtime_calls[0]["judges"] == ["gemini"]
    assert realtime_calls[0]["doi_filter"] == all_dois


# In plain English: --limit must still work as an explicit per-journal cap
# in batch mode (only the *default*, uncapped case was buggy).
def test_evaluate_batch_mode_limit_still_caps_per_journal(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    import batch_utils
    import evaluator

    dois_by_journal = {
        "jvim": ["10.9999/j1.1", "10.9999/j1.2", "10.9999/j1.3"],
        "javma": ["10.9999/j2.1", "10.9999/j2.2"],
    }
    _write_fake_summaries_with_journals(
        _wired_paths["summaries_path"], _wired_paths["processed_dir"], dois_by_journal,
    )

    seen_dois: set[str] = set()
    monkeypatch.setattr(
        batch_utils, "run_batch_evaluation",
        lambda *, doi_filter, **_kw: seen_dois.update(doi_filter) or {"submitted": []},
    )
    monkeypatch.setattr(
        evaluator, "run_evaluation",
        lambda *, doi_filter, **_kw: seen_dois.update(doi_filter) or {"success": 0, "failed": 0},
    )

    ret = _run_evaluate(["evaluate", "--mode", "batch", "--force", "--limit", "1"])

    assert ret == 0
    # 1 per journal x 2 journals = 2, not all 5.
    assert len(seen_dois) == 2


def _write_summarize_all_txt(
    txt_dir: Path, processed_dir: Path, *, doi: str, stem: str = "paperA",
) -> None:
    """Write one summarize-all processed-text comparison file plus its
    matching data/processed/*.jsonl cache, mirroring the real on-disk shape
    of `run_phase3.py summarize-all` output.

    In plain English: builds a fake but realistic .txt file, in exactly the
    format `summarize-all` writes, so the tests below can check that
    `evaluate --input-mode dev` (which reads these .txt files) parses them
    correctly.
    """
    txt_dir.mkdir(parents=True, exist_ok=True)
    processed_dir.mkdir(parents=True, exist_ok=True)
    filename = f"{stem}.jsonl"
    (processed_dir / filename).write_text(
        json.dumps({"doi": doi, "text": "Reference body text. " * 30}) + "\n",
        encoding="utf-8",
    )
    sep = "=" * 78
    text = "\n".join([
        "Summary Source: Processed Text",
        f"Source File: {filename}",
        f"DOI: {doi}",
        f"Slug: {stem}",
        "Generated At: 2026-07-07T01:50:57.522999+00:00",
        "",
        "This file contains one summary from each configured model provider.",
        "Compare the provider sections below against the same article source.",
        "",
        sep, "OPENAI SUMMARY", sep,
        "Status: success",
        "Model Version: gpt-5.4-test",
        "Timestamp: 2026-07-07T01:51:20.853179+00:00",
        "Input Tokens: 100",
        "Output Tokens: 50",
        "",
        "A candidate summary for this article.",
        "",
    ]) + "\n"
    (txt_dir / f"{stem}.txt").write_text(text, encoding="utf-8")


# In plain English: checks the priority order that _resolve_eval_input_mode
# (in run_phase3.py) uses to decide where `evaluate` reads summaries from —
# confirming that an explicit --input-mode flag always wins, that --mode dev
# defaults to the folder-driven loop unless overridden, and that 'auto'
# expands to the right folder for each mode.
def test_resolve_eval_input_mode_precedence(monkeypatch: pytest.MonkeyPatch) -> None:
    import run_phase3

    monkeypatch.delenv("EVAL_INPUT_MODE", raising=False)
    # Default for non-dev modes: jsonl.
    assert run_phase3._resolve_eval_input_mode("single", None) == "jsonl"
    # Dev mode with no --input-mode always resolves to the folder-driven loop,
    # regardless of EVAL_INPUT_MODE.
    assert run_phase3._resolve_eval_input_mode("dev", None) == "dev-jsonl"

    # .env value applies when there's no CLI override (non-dev mode).
    monkeypatch.setenv("EVAL_INPUT_MODE", "dev")
    assert run_phase3._resolve_eval_input_mode("single", None) == "dev"
    # ...but EVAL_INPUT_MODE never overrides the dev-mode default.
    assert run_phase3._resolve_eval_input_mode("dev", None) == "dev-jsonl"

    # CLI override always wins — including forcing a dev run back to jsonl.
    assert run_phase3._resolve_eval_input_mode("single", "regular") == "regular"
    assert run_phase3._resolve_eval_input_mode("dev", "jsonl") == "jsonl"
    assert run_phase3._resolve_eval_input_mode("dev", "dev") == "dev"

    # auto expands based on the active PHASE3_MODE (explicit CLI, so no dev default).
    assert run_phase3._resolve_eval_input_mode("dev", "auto") == "dev"
    assert run_phase3._resolve_eval_input_mode("single", "auto") == "regular"
    assert run_phase3._resolve_eval_input_mode("batch", "auto") == "regular"

    # Unknown value falls back to jsonl (non-dev mode).
    monkeypatch.setenv("EVAL_INPUT_MODE", "nonsense")
    assert run_phase3._resolve_eval_input_mode("single", None) == "jsonl"


# In plain English: checks that `evaluate --input-mode dev` correctly
# switches to reading the summarize-all comparison folder instead of the
# main summaries.jsonl file, and that it produces the right number of
# evaluation rows (one article judged by all 3 judges = 3 rows).
def test_evaluate_dev_input_mode_reads_txt_folder_not_jsonl(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--input-mode dev picks WHICH papers to judge from
    data/dev_tests/summaries_txt, but scores the prose summary_text from
    data/summaries.jsonl — the same surface every other input mode judges."""
    import run_phase3
    import summarize_all_ingest

    txt_dir = _wired_paths["manifest_dir"] / "dev_tests_summaries_txt"
    monkeypatch.setattr(run_phase3, "DEV_TESTS_SUMMARIES_TXT_DIR", txt_dir)
    monkeypatch.setattr(summarize_all_ingest, "PROCESSED_DIR", _wired_paths["processed_dir"])
    _write_summarize_all_txt(
        txt_dir, _wired_paths["processed_dir"], doi="10.9999/txt.0001",
    )
    _write_fake_summaries(
        _wired_paths["summaries_path"], _wired_paths["processed_dir"], ["10.9999/txt.0001"],
    )

    result = _run_evaluate(["evaluate", "--mode", "test", "--input-mode", "dev"])

    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert data["status"] == "completed"
    assert data["selected_instance_ids"] == ["10.9999/txt.0001"]
    assert data["evaluation_config"]["slice_config"]["type"] == "summarize_all_txt"
    assert data["evaluation_config"]["slice_config"]["input_mode"] == "dev"

    from evaluator import JURY_PANEL

    # PHASE3_MODE=test, so the write guard diverts these mock rows away from
    # the production ledger into the _dryrun sibling. See the guard tests in
    # tests/test_evaluator.py for why.
    _dry_run_evaluations = _wired_paths["evaluations_path"].with_name(
        "evaluations_dryrun.jsonl")
    assert not _wired_paths["evaluations_path"].exists()
    rows = [
        json.loads(line)
        for line in _dry_run_evaluations.read_text(encoding="utf-8").splitlines()
    ]
    # One article × one summarizer × the 3-judge default = 3 rows.
    assert len(rows) == 3
    assert {row["doi"] for row in rows} == {"10.9999/txt.0001"}
    assert {row["summarizer"] for row in rows} == {"openai"}
    assert {row["judge"] for row in rows} == set(JURY_PANEL)


# In plain English: checks that if you ask `evaluate` to read from a
# --input-mode dev folder that's empty (nothing to judge), it fails cleanly
# with an error code instead of crashing or silently doing nothing.
def test_evaluate_dev_input_mode_no_files_returns_error(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    import run_phase3

    empty_txt_dir = _wired_paths["manifest_dir"] / "empty_dev_txt"
    monkeypatch.setattr(run_phase3, "DEV_TESTS_SUMMARIES_TXT_DIR", empty_txt_dir)

    result = _run_evaluate(["evaluate", "--mode", "test", "--input-mode", "dev"])

    assert result == 1
    # No manifest is written when there is nothing to evaluate.
    assert list(_wired_paths["manifest_dir"].glob("run_manifest_*.json")) == []


def _journal_records(journal: str, n: int) -> list[dict]:
    """In plain English: builds n fake manifest rows, all belonging to the
    given fake journal name, for the round-robin sampling tests below."""
    return [{"doi": f"10.1/{journal}.{i}", "journal": journal} for i in range(n)]


# The next several tests all check _sample_round_robin_by_journal — the
# function in run_phase3.py that picks which papers `summarize --mode dev`
# summarizes, one per journal, before any money is spent.

def test_sample_round_robin_by_journal_one_per_journal_when_limit_matches() -> None:
    """limit == number of journals -> exactly one paper per journal."""
    import run_phase3

    by_journal = {
        "jvim": _journal_records("jvim", 3),
        "javma": _journal_records("javma", 3),
        "jfms": _journal_records("jfms", 3),
    }

    selected = run_phase3._sample_round_robin_by_journal(by_journal, limit=3, seed=42)

    assert len(selected) == 3
    assert {r["journal"] for r in selected} == {"jvim", "javma", "jfms"}


def test_sample_round_robin_by_journal_limit_below_journal_count() -> None:
    """limit < number of journals -> only that many journals are touched.

    In plain English: if you ask for fewer papers than there are journals,
    only some journals get picked from — not every journal gets a paper.
    """
    import run_phase3

    by_journal = {
        "jvim": _journal_records("jvim", 1),
        "javma": _journal_records("javma", 1),
        "jfms": _journal_records("jfms", 1),
    }

    selected = run_phase3._sample_round_robin_by_journal(by_journal, limit=2, seed=1)

    assert len(selected) == 2
    journals = {r["journal"] for r in selected}
    assert len(journals) == 2
    assert journals.issubset({"jvim", "javma", "jfms"})


def test_sample_round_robin_by_journal_spills_over_when_limit_exceeds_journals() -> None:
    """limit > number of journals -> every journal gets 1 before any gets 2.

    In plain English: if you ask for MORE papers than there are journals,
    every journal gets one paper first, and only then does a second round
    start handing out extra papers — no journal gets skipped in favor of
    another journal getting two.
    """
    import run_phase3

    by_journal = {
        "jvim": _journal_records("jvim", 3),
        "javma": _journal_records("javma", 3),
    }

    selected = run_phase3._sample_round_robin_by_journal(by_journal, limit=3, seed=7)

    assert len(selected) == 3
    counts: dict[str, int] = {}
    for r in selected:
        counts[r["journal"]] = counts.get(r["journal"], 0) + 1
    # Both journals got at least 1 before either got a 2nd (round-robin, not
    # "drain journal A first").
    assert counts.get("jvim", 0) >= 1
    assert counts.get("javma", 0) >= 1
    assert sum(counts.values()) == 3


# In plain English: confirms that "random" paper selection is actually
# reproducible — running the same selection twice with the same seed number
# picks the exact same papers both times, not a different random draw.
def test_sample_round_robin_by_journal_is_deterministic_given_seed() -> None:
    import run_phase3

    by_journal = {
        "jvim": _journal_records("jvim", 5),
        "javma": _journal_records("javma", 5),
    }

    first = run_phase3._sample_round_robin_by_journal(by_journal, limit=2, seed=42)
    second = run_phase3._sample_round_robin_by_journal(by_journal, limit=2, seed=42)

    assert [r["doi"] for r in first] == [r["doi"] for r in second]


def test_sample_round_robin_by_journal_empty_journal_is_dropped() -> None:
    """A journal with no eligible records never gets selected from.

    In plain English: a journal that has zero eligible papers to pick from
    is simply skipped, instead of causing an error or an empty pick.
    """
    import run_phase3

    by_journal = {
        "jvim": _journal_records("jvim", 1),
        "empty": [],
    }

    selected = run_phase3._sample_round_robin_by_journal(by_journal, limit=5, seed=42)

    assert len(selected) == 1
    assert selected[0]["journal"] == "jvim"


# In plain English: checks that _load_manifest_by_journal (used by dev-mode
# summarize to decide which papers are even eligible) correctly excludes
# papers that have no journal name, or that were never actually extracted
# into cached text — only "ready to summarize" papers make it through.
def test_load_manifest_by_journal_only_keeps_records_with_cached_text(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """
    manifest.jsonl rows without a cached processed-text file (never
    downloaded, or extraction failed) must be excluded — this is what makes
    noise manifest rows fall out of dev-mode journal-random selection
    automatically, without an explicit journal allowlist.
    """
    import prepare_texts
    import run_phase3
    from file_paths import doi_to_slug

    manifest_path = tmp_path / "manifest.jsonl"
    processed = tmp_path / "processed"
    processed.mkdir()
    monkeypatch.setattr(prepare_texts, "PROCESSED_DIR", processed)

    has_text_doi = "10.9999/has_text.0001"
    no_text_doi = "10.9999/no_text.0001"
    no_journal_doi = "10.9999/no_journal.0001"

    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write(json.dumps({"doi": has_text_doi, "journal": "JVIM"}) + "\n")
        f.write(json.dumps({"doi": no_text_doi, "journal": "JVIM"}) + "\n")
        f.write(json.dumps({"doi": no_journal_doi, "journal": ""}) + "\n")

    slug = doi_to_slug(has_text_doi)
    (processed / f"{slug}.jsonl").write_text(
        json.dumps({"doi": has_text_doi, "slug": slug, "text": "body"}) + "\n",
        encoding="utf-8",
    )

    by_journal = run_phase3._load_manifest_by_journal(manifest_path, "processed")

    assert list(by_journal.keys()) == ["jvim"]
    assert [r["doi"] for r in by_journal["jvim"]] == [has_text_doi]


def test_cmd_summarize_dev_mode_selects_one_per_journal_and_writes_readable_folder(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """
    In plain English: a full, mocked, no-cost end-to-end check that running
    `summarize --mode dev` really does pick one paper per journal, write
    exactly that many rows to summaries.jsonl, and write one readable .txt
    file per selected paper to data/dev_summaries_jsonl/ — i.e. this checks
    the whole dev-mode summarize pipeline works together correctly, not just
    one isolated piece of it.

    End-to-end (mocked, PHASE3_MODE=test/DRY_RUN) check of the dev-mode
    journal-random wiring in cmd_summarize: exactly one DOI per journal goes
    through --doi-filter, data/summaries.jsonl gets exactly that many rows,
    and data/dev_summaries_jsonl/ gets one readable .txt per selected paper.
    """
    import prepare_texts
    import run_phase3
    import summarizer
    from file_paths import doi_to_slug

    monkeypatch.setenv("DRY_RUN", "true")
    monkeypatch.setattr(summarizer, "DRY_RUN", True)
    monkeypatch.setenv("PHASE3_DEV_LIMIT", "2")
    monkeypatch.setenv("PHASE3_DEV_SAMPLE_SEED", "42")

    manifest_path = tmp_path / "manifest.jsonl"
    processed = tmp_path / "processed"
    processed.mkdir()
    summaries_path = tmp_path / "summaries.jsonl"
    dev_dir = tmp_path / "dev_summaries_jsonl"

    journals = {"jvim": 3, "javma": 3}
    dois_by_journal: dict[str, list[str]] = {}
    with open(manifest_path, "w", encoding="utf-8") as f:
        for journal, n in journals.items():
            dois = [f"10.9999/{journal}.{i:04d}" for i in range(n)]
            dois_by_journal[journal] = dois
            for doi in dois:
                record = {"doi": doi, "journal": journal, "title": f"Paper {doi}"}
                f.write(json.dumps(record) + "\n")
                slug = doi_to_slug(doi)
                (processed / f"{slug}.jsonl").write_text(
                    json.dumps({"doi": doi, "slug": slug, "text": "Body text. " * 30}) + "\n",
                    encoding="utf-8",
                )

    monkeypatch.setattr(run_phase3, "PROCESSED_DIR", processed)
    monkeypatch.setattr(prepare_texts, "PROCESSED_DIR", processed)
    monkeypatch.setattr(summarizer, "PROCESSED_DIR", processed)
    monkeypatch.setattr(summarizer, "SUMMARIES_PATH", summaries_path)
    monkeypatch.setattr(run_phase3, "DEV_SUMMARIES_JSONL_DIR", dev_dir)
    # confirm_real_batch's --force bypass writes an audit line to LOGS_DIR —
    # redirect it so this test doesn't pollute the real data/logs/phase3_safety.log.
    monkeypatch.setattr(summarizer, "LOGS_DIR", tmp_path / "logs")

    parser = run_phase3.build_parser()
    args = parser.parse_args([
        "summarize", "--mode", "dev", "--manifest", str(manifest_path),
        "--providers", "openai", "--force",
    ])
    result = run_phase3.cmd_summarize(args)

    assert result == 0

    rows = [
        json.loads(line) for line in summaries_path.read_text(encoding="utf-8").splitlines()
    ]
    assert len(rows) == 2
    assert {row["journal"] for row in rows} == {"jvim", "javma"}

    txt_files = list(dev_dir.glob("*.txt"))
    assert len(txt_files) == 2

    # Prose sibling: one file per selected paper under prose/, carrying the
    # word-count header. The bullet files above stay at the folder top level so
    # the *.txt discovery readers (eval source / resume) are unaffected.
    prose_files = list((dev_dir / "prose").glob("*.txt"))
    assert len(prose_files) == 2
    assert "Summary (prose):" in prose_files[0].read_text(encoding="utf-8")


def _write_dev_readable_txt(folder: Path, doi: str, *, suffix: str | None = None) -> Path:
    """Write a minimal dev-mode readable .txt whose first line is ``DOI: <doi>``.

    In plain English: a shortcut for tests to "pretend" a readable .txt file
    for a given paper already exists in a dev folder, without going through
    a real summarize or evaluate run.
    """
    from file_paths import doi_to_slug

    folder.mkdir(parents=True, exist_ok=True)
    stem = doi_to_slug(doi)
    if suffix:
        stem = f"{stem}__{suffix}"
    path = folder / f"{stem}.txt"
    path.write_text(f"DOI: {doi}\nJournal: jvim\n\nbody\n", encoding="utf-8")
    return path


# In plain English: checks that reading DOIs (paper IDs) back out of a dev
# folder correctly identifies each unique paper by its "DOI:" header line —
# even when the same paper has two different files from two separate runs —
# and returns an empty result (not an error) for a folder that doesn't exist.
def test_read_dois_from_dev_folder_parses_headers(tmp_path: Path) -> None:
    # The DOI-header reader lives in eval_instances (single source of truth
    # shared by run_phase3 and pilot_human_review); run_phase3 imports it.
    from eval_instances import read_dois_from_dev_folder

    folder = tmp_path / "dev_summaries_jsonl"
    # Same DOI under two timestamped suffixes must collapse to one DOI (we parse
    # the header, not the filename).
    _write_dev_readable_txt(folder, "10.1/aaa", suffix="run_A")
    _write_dev_readable_txt(folder, "10.1/aaa", suffix="run_B")
    _write_dev_readable_txt(folder, "10.2/bbb")

    assert read_dois_from_dev_folder(folder) == {"10.1/aaa", "10.2/bbb"}
    # Missing folder → empty set, not an error.
    assert read_dois_from_dev_folder(tmp_path / "nope") == set()


def _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3):
    """Point the dev folders at tmp dirs; return (source_dir, evals_dir).

    In plain English: redirects the "folder-driven dev evaluate loop" (see
    _cmd_evaluate_from_dev_jsonl in run_phase3.py) to scratch folders for
    this test, just like _wired_paths does for the other data files.
    """
    source_dir = _wired_paths["manifest_dir"] / "dev_summaries_jsonl"
    evals_dir = _wired_paths["manifest_dir"] / "dev_evals_jsonl"
    detail_dir = _wired_paths["manifest_dir"] / "dev_detailEval_reports"
    monkeypatch.setattr(run_phase3, "DEV_SUMMARIES_JSONL_DIR", source_dir)
    monkeypatch.setattr(run_phase3, "DEV_EVALS_JSONL_DIR", evals_dir)
    monkeypatch.setattr(run_phase3, "DEV_DETAIL_EVAL_REPORTS_DIR", detail_dir)
    return source_dir, evals_dir


def test_evaluate_dev_jsonl_reads_dev_folder_and_writes_dev_evals(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`evaluate` in dev-jsonl mode judges exactly the DOIs sitting in
    data/dev_summaries_jsonl/ and mirrors the scores into data/dev_evals_jsonl/.

    In plain English: checks the main folder-driven dev-evaluate loop
    end-to-end — the papers sitting in the dev-summaries folder get judged,
    and a readable result file for each one is written to the dev-evals folder.
    """
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    dois = ["10.9999/dev.0001", "10.9999/dev.0002"]
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], dois)
    for doi in dois:
        _write_dev_readable_txt(source_dir, doi, suffix="run_x")

    # --mode test keeps this at $0/mock while --input-mode dev-jsonl forces the
    # new folder-driven branch.
    result = _run_evaluate(["evaluate", "--mode", "test", "--input-mode", "dev-jsonl"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert data["status"] == "completed"
    assert data["evaluation_config"]["slice_config"]["type"] == "dev_jsonl"
    assert data["selected_instance_ids"] == sorted(dois)

    eval_files = sorted(evals_dir.glob("*.txt"))
    assert len(eval_files) == 2
    for path in eval_files:
        assert path.read_text(encoding="utf-8").startswith("DOI:")


# In plain English: `--source-dir` lets you judge a folder other than the
# default data/dev_summaries_jsonl/ — an --output-subdir pool, or the single/
# batch readable folders — while results still land in data/dev_evals_jsonl/.
# The folder actually used must also be recorded in the run manifest, or
# provenance goes ambiguous once runs mix sources.
def test_evaluate_dev_jsonl_source_dir_overrides_default_folder(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    import run_phase3

    default_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    alt_dir = _wired_paths["manifest_dir"] / "batch_summaries_jsonl"
    dois = ["10.9999/alt.0001"]
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], dois)
    # A decoy in the default folder that must NOT be judged.
    _write_dev_readable_txt(default_dir, "10.9999/decoy.0001")
    for doi in dois:
        _write_dev_readable_txt(alt_dir, doi)

    result = _run_evaluate([
        "evaluate", "--mode", "test", "--input-mode", "dev-jsonl",
        "--source-dir", str(alt_dir),
    ])
    assert result == 0

    data = json.loads(_find_manifest(_wired_paths["manifest_dir"]).read_text(encoding="utf-8"))
    assert data["selected_instance_ids"] == dois  # decoy not judged
    assert data["evaluation_config"]["slice_config"]["source_dir"] == str(alt_dir)
    assert data["dataset_path"] == str(alt_dir)


# In plain English: the readable-folder readers glob *.txt non-recursively, so
# an --output-subdir pool is invisible to them. That silence is the trap this
# warning exists to break: prose/ is skipped quietly (it's the same papers),
# but any other subfolder gets named out loud.
def test_warn_about_unread_subfolders_names_only_non_prose_subdirs(tmp_path: Path, capsys) -> None:
    import run_phase3

    folder = tmp_path / "dev_summaries_jsonl"
    _write_dev_readable_txt(folder, "10.1/top")
    _write_dev_readable_txt(folder / "prose", "10.1/top")          # expected sibling
    _write_dev_readable_txt(folder / "promptv2", "10.2/hidden")    # invisible pool
    (folder / "empty_dir").mkdir()                                  # no .txt -> ignored

    skipped = run_phase3._warn_about_unread_subfolders(folder)

    assert skipped == ["promptv2"]
    out = capsys.readouterr().out
    assert "promptv2" in out
    assert "--source-dir" in out
    assert "prose" not in out.replace("promptv2", "")

    # Missing folder is silent, not an error.
    assert run_phase3._warn_about_unread_subfolders(tmp_path / "nope") == []


def test_evaluate_dev_jsonl_skips_already_evaluated(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A DOI already present in data/dev_evals_jsonl/ is not re-judged.

    In plain English: confirms the incremental/resume behavior — a paper
    that's already been judged in a previous dev run is skipped this time,
    so re-running `evaluate --mode dev` doesn't waste money re-judging
    something already done.
    """
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    dois = ["10.9999/dev.0001", "10.9999/dev.0002"]
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], dois)
    for doi in dois:
        _write_dev_readable_txt(source_dir, doi)
    # Pretend dev.0001 was judged in an earlier run.
    _write_dev_readable_txt(evals_dir, "10.9999/dev.0001")

    result = _run_evaluate(["evaluate", "--mode", "test", "--input-mode", "dev-jsonl"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert data["selected_instance_ids"] == ["10.9999/dev.0002"]

    # PHASE3_MODE=test, so the write guard diverts these mock rows away from
    # the production ledger into the _dryrun sibling. See the guard tests in
    # tests/test_evaluator.py for why.
    _dry_run_evaluations = _wired_paths["evaluations_path"].with_name(
        "evaluations_dryrun.jsonl")
    assert not _wired_paths["evaluations_path"].exists()
    rows = [
        json.loads(line)
        for line in _dry_run_evaluations.read_text(encoding="utf-8").splitlines()
    ]
    assert {row["doi"] for row in rows} == {"10.9999/dev.0002"}


def test_evaluate_dev_jsonl_no_resume_reincludes_done(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--no-resume re-includes DOIs already in data/dev_evals_jsonl/.

    In plain English: confirms that passing --no-resume overrides the
    skip-already-done behavior above, forcing every paper (even ones already
    judged) to be re-judged.
    """
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    dois = ["10.9999/dev.0001", "10.9999/dev.0002"]
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], dois)
    for doi in dois:
        _write_dev_readable_txt(source_dir, doi)
    _write_dev_readable_txt(evals_dir, "10.9999/dev.0001")

    result = _run_evaluate(
        ["evaluate", "--mode", "test", "--input-mode", "dev-jsonl", "--no-resume"]
    )
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert data["selected_instance_ids"] == sorted(dois)


# In plain English: if the dev-summaries folder is empty (no papers to
# judge), `evaluate --mode dev` should fail cleanly with an error code
# instead of pretending to succeed.
def test_evaluate_dev_jsonl_empty_source_returns_error(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    import run_phase3

    _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    result = _run_evaluate(["evaluate", "--mode", "test", "--input-mode", "dev-jsonl"])
    assert result == 1


# In plain English: if every paper in the dev-summaries folder has already
# been judged, `evaluate --mode dev` should exit successfully doing nothing
# (a "no-op") rather than erroring out or writing a pointless empty manifest.
def test_evaluate_dev_jsonl_all_done_returns_zero_noop(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    _write_fake_summaries(
        _wired_paths["summaries_path"], _wired_paths["processed_dir"], ["10.9999/dev.0001"]
    )
    _write_dev_readable_txt(source_dir, "10.9999/dev.0001")
    _write_dev_readable_txt(evals_dir, "10.9999/dev.0001")

    result = _run_evaluate(["evaluate", "--mode", "test", "--input-mode", "dev-jsonl"])
    # Everything already evaluated → clean no-op, no manifest written.
    assert result == 0
    assert not list(_wired_paths["manifest_dir"].glob("run_manifest_*.json"))


# ---------------------------------------------------------------------------
# evaluate --mode dev: per-run cap + journal-balanced sampling of the
# PENDING pool (the feature this block tests). Unlike the tests above (which
# all use `--mode test`, where the cap is intentionally never applied), these
# drive a real `--mode dev` profile with `evaluator.run_evaluation` stubbed
# out so no live judge call happens, matching the pattern
# `test_evaluate_marks_manifest_failed_on_exception` already uses. `--force`
# bypasses the interactive "type yes" confirmation; both evaluator.LOGS_DIR
# (the --force audit line) and run_phase3.LOGS_DIR (the new unmapped-journal
# warning log) are redirected to tmp_path so no real log file is touched.
# ---------------------------------------------------------------------------

def _write_manifest_journals(manifest_path: Path, dois_by_journal: dict[str, list[str]]) -> None:
    """Write a manifest.jsonl row {"doi", "journal"} for every DOI given."""
    with open(manifest_path, "w", encoding="utf-8") as f:
        for journal, dois in dois_by_journal.items():
            for doi in dois:
                f.write(json.dumps({"doi": doi, "journal": journal}) + "\n")


def _stub_dev_eval_wiring(_wired_paths, monkeypatch: pytest.MonkeyPatch, run_phase3):
    """Redirect LOGS_DIR (both modules) and stub evaluator.run_evaluation.

    In plain English: lets these tests drive a real (non-test) `--mode dev`
    run with `--force`, without ever making a live judge call or writing to
    the real project's data/logs/ folder.
    """
    import evaluator

    logs_dir = _wired_paths["manifest_dir"] / "logs"
    monkeypatch.setattr(evaluator, "LOGS_DIR", logs_dir)
    monkeypatch.setattr(run_phase3, "LOGS_DIR", logs_dir)
    monkeypatch.setattr(evaluator, "run_evaluation", lambda **kwargs: {"failed": 0})


def test_evaluate_dev_jsonl_caps_and_balances_across_journals(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A pending pool bigger than --limit is capped and spread evenly across
    journals, one per journal per round -- mirroring `summarize --mode dev`'s
    own round-robin-by-journal picker on the judging side."""
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    _stub_dev_eval_wiring(_wired_paths, monkeypatch, run_phase3)

    dois_by_journal = {
        "jvim": [f"10.9999/jvim.{i:04d}" for i in range(3)],
        "javma": [f"10.9999/javma.{i:04d}" for i in range(3)],
        "jfms": [f"10.9999/jfms.{i:04d}" for i in range(3)],
    }
    all_dois = [doi for dois in dois_by_journal.values() for doi in dois]
    _write_manifest_journals(_wired_paths["manifest_dir"] / "manifest.jsonl", dois_by_journal)
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], all_dois)
    for doi in all_dois:
        _write_dev_readable_txt(source_dir, doi)

    result = _run_evaluate(["evaluate", "--mode", "dev", "--limit", "3", "--force"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    selected = data["selected_instance_ids"]
    assert len(selected) == 3

    doi_to_journal = {doi: j for j, dois in dois_by_journal.items() for doi in dois}
    assert {doi_to_journal[doi] for doi in selected} == {"jvim", "javma", "jfms"}

    slice_config = data["evaluation_config"]["slice_config"]
    assert slice_config["articles_pending_before_sampling"] == 9
    assert slice_config["articles_to_judge"] == 3
    assert slice_config["sampling"]["limit"] == 3
    assert slice_config["sampling"]["journal_counts"] == {"jvim": 1, "javma": 1, "jfms": 1}


def test_evaluate_dev_jsonl_pool_under_cap_is_not_sampled(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A pending pool at or below the cap is judged in full, unchanged from
    the pre-cap behavior -- a regression guard."""
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    _stub_dev_eval_wiring(_wired_paths, monkeypatch, run_phase3)

    dois_by_journal = {"jvim": ["10.9999/jvim.0000"], "javma": ["10.9999/javma.0000"]}
    all_dois = [doi for dois in dois_by_journal.values() for doi in dois]
    _write_manifest_journals(_wired_paths["manifest_dir"] / "manifest.jsonl", dois_by_journal)
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], all_dois)
    for doi in all_dois:
        _write_dev_readable_txt(source_dir, doi)

    result = _run_evaluate(["evaluate", "--mode", "dev", "--limit", "5", "--force"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert sorted(data["selected_instance_ids"]) == sorted(all_dois)
    assert data["evaluation_config"]["slice_config"]["sampling"] is None


def test_evaluate_dev_jsonl_limit_overrides_env_default(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--limit N overrides PHASE3_DEV_LIMIT for a single dev-jsonl run."""
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    _stub_dev_eval_wiring(_wired_paths, monkeypatch, run_phase3)
    # A generous env default would not exercise the override, so pin it low
    # and then ask for even fewer via --limit.
    monkeypatch.setenv("PHASE3_DEV_LIMIT", "50")

    dois_by_journal = {
        "jvim": [f"10.9999/jvim.{i:04d}" for i in range(3)],
        "javma": [f"10.9999/javma.{i:04d}" for i in range(3)],
    }
    all_dois = [doi for dois in dois_by_journal.values() for doi in dois]
    _write_manifest_journals(_wired_paths["manifest_dir"] / "manifest.jsonl", dois_by_journal)
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], all_dois)
    for doi in all_dois:
        _write_dev_readable_txt(source_dir, doi)

    result = _run_evaluate(["evaluate", "--mode", "dev", "--limit", "2", "--force"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    selected = data["selected_instance_ids"]
    assert len(selected) == 2
    doi_to_journal = {doi: j for j, dois in dois_by_journal.items() for doi in dois}
    assert {doi_to_journal[doi] for doi in selected} == {"jvim", "javma"}


def test_evaluate_dev_jsonl_test_mode_bypasses_cap(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--mode test always judges the whole pending pool, ignoring
    PHASE3_DEV_LIMIT entirely -- the free/mock path must keep this
    guarantee for the existing dev-jsonl tests above."""
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    dois = [f"10.9999/test.{i:04d}" for i in range(8)]
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], dois)
    for doi in dois:
        _write_dev_readable_txt(source_dir, doi)

    result = _run_evaluate(["evaluate", "--mode", "test", "--input-mode", "dev-jsonl"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert sorted(data["selected_instance_ids"]) == sorted(dois)
    assert data["evaluation_config"]["slice_config"]["sampling"] is None


def test_evaluate_dev_jsonl_no_resume_bypasses_cap(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--no-resume keeps meaning "re-judge everything in the source folder",
    not "re-judge a capped sample of it"."""
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    _stub_dev_eval_wiring(_wired_paths, monkeypatch, run_phase3)
    # A cap smaller than the pool proves --no-resume really does bypass it,
    # not just happen to have a generous enough limit.
    monkeypatch.setenv("PHASE3_DEV_LIMIT", "2")

    dois_by_journal = {
        "jvim": [f"10.9999/jvim.{i:04d}" for i in range(3)],
        "javma": [f"10.9999/javma.{i:04d}" for i in range(3)],
    }
    all_dois = [doi for dois in dois_by_journal.values() for doi in dois]
    _write_manifest_journals(_wired_paths["manifest_dir"] / "manifest.jsonl", dois_by_journal)
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], all_dois)
    for doi in all_dois:
        _write_dev_readable_txt(source_dir, doi)
    # One DOI already marked done -- --no-resume must re-include it too.
    _write_dev_readable_txt(evals_dir, all_dois[0])

    result = _run_evaluate(["evaluate", "--mode", "dev", "--no-resume", "--force"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert sorted(data["selected_instance_ids"]) == sorted(all_dois)


def test_evaluate_dev_jsonl_deferred_papers_picked_up_next_run(
    _wired_paths, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Papers left out by the cap aren't lost -- a follow-up run judges the
    remainder, since they were never marked done."""
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    _stub_dev_eval_wiring(_wired_paths, monkeypatch, run_phase3)

    dois_by_journal = {
        "jvim": [f"10.9999/jvim.{i:04d}" for i in range(3)],
        "javma": [f"10.9999/javma.{i:04d}" for i in range(3)],
    }
    all_dois = [doi for dois in dois_by_journal.values() for doi in dois]
    _write_manifest_journals(_wired_paths["manifest_dir"] / "manifest.jsonl", dois_by_journal)
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], all_dois)
    for doi in all_dois:
        _write_dev_readable_txt(source_dir, doi)

    result_1 = _run_evaluate(["evaluate", "--mode", "dev", "--limit", "3", "--force"])
    assert result_1 == 0
    manifest_1 = _find_manifest(_wired_paths["manifest_dir"])
    selected_1 = set(json.loads(manifest_1.read_text(encoding="utf-8"))["selected_instance_ids"])
    assert len(selected_1) == 3

    # The stubbed run_evaluation never appends real evaluations.jsonl rows,
    # so write_dev_eval_jsonl_outputs would write 0 files -- manually mark
    # this run's selection as done, standing in for what that function would
    # have written on a real (non-stubbed) run.
    for doi in selected_1:
        _write_dev_readable_txt(evals_dir, doi)

    result_2 = _run_evaluate(["evaluate", "--mode", "dev", "--limit", "3", "--force"])
    assert result_2 == 0
    # create_run_id() has 1-second granularity, so whether these two runs share
    # a manifest filename depends on wall-clock luck: land in the same second
    # and the second write overwrites the first, straddle a second boundary and
    # there are two files. Either way the run we want is the newest one, and
    # selected_1 was already captured in memory before this second call. (Do not
    # use _find_manifest here -- it asserts exactly one manifest exists.)
    manifest_2 = sorted(_wired_paths["manifest_dir"].glob("run_manifest_*.json"))[-1]
    selected_2 = set(json.loads(manifest_2.read_text(encoding="utf-8"))["selected_instance_ids"])

    assert selected_2.isdisjoint(selected_1)
    assert selected_1 | selected_2 == set(all_dois)


def test_evaluate_dev_jsonl_unmapped_journal_excluded_and_warned(
    _wired_paths, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str],
) -> None:
    """A pending DOI with no journal in manifest.jsonl is excluded from the
    balanced sample (not silently bucketed as "unknown") and warned about --
    matching how the non-dev jsonl evaluate path already treats unmapped
    DOIs."""
    import run_phase3

    source_dir, evals_dir = _wire_dev_jsonl(_wired_paths, monkeypatch, run_phase3)
    _stub_dev_eval_wiring(_wired_paths, monkeypatch, run_phase3)

    dois_by_journal = {
        "jvim": [f"10.9999/jvim.{i:04d}" for i in range(2)],
        "javma": [f"10.9999/javma.{i:04d}" for i in range(2)],
    }
    unmapped_doi = "10.9999/no_journal.0000"
    all_dois = [doi for dois in dois_by_journal.values() for doi in dois] + [unmapped_doi]
    _write_manifest_journals(_wired_paths["manifest_dir"] / "manifest.jsonl", dois_by_journal)
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], all_dois)
    for doi in all_dois:
        _write_dev_readable_txt(source_dir, doi)

    result = _run_evaluate(["evaluate", "--mode", "dev", "--limit", "3", "--force"])
    assert result == 0

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    assert unmapped_doi not in data["selected_instance_ids"]

    captured = capsys.readouterr()
    assert "WARNING" in captured.out
    assert unmapped_doi in captured.out


def _setup_dev_summarize(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Shared wiring for the dev-mode summarize skip tests. Returns paths.

    In plain English: sets up a fake manifest with 2 journals x 3 papers
    each, all pointed at scratch folders, so the tests below can check
    dev-mode's "skip already-summarized papers" behavior without touching
    real project data.
    """
    import prepare_texts
    import run_phase3
    import summarizer
    from file_paths import doi_to_slug

    monkeypatch.setenv("DRY_RUN", "true")
    monkeypatch.setattr(summarizer, "DRY_RUN", True)
    monkeypatch.setenv("PHASE3_DEV_LIMIT", "2")
    monkeypatch.setenv("PHASE3_DEV_SAMPLE_SEED", "42")

    manifest_path = tmp_path / "manifest.jsonl"
    processed = tmp_path / "processed"
    processed.mkdir()
    summaries_path = tmp_path / "summaries.jsonl"
    dev_dir = tmp_path / "dev_summaries_jsonl"

    dois_by_journal: dict[str, list[str]] = {}
    with open(manifest_path, "w", encoding="utf-8") as f:
        for journal in ("jvim", "javma"):
            dois = [f"10.9999/{journal}.{i:04d}" for i in range(3)]
            dois_by_journal[journal] = dois
            for doi in dois:
                f.write(json.dumps({"doi": doi, "journal": journal, "title": f"Paper {doi}"}) + "\n")
                slug = doi_to_slug(doi)
                (processed / f"{slug}.jsonl").write_text(
                    json.dumps({"doi": doi, "slug": slug, "text": "Body text. " * 30}) + "\n",
                    encoding="utf-8",
                )

    monkeypatch.setattr(run_phase3, "PROCESSED_DIR", processed)
    monkeypatch.setattr(prepare_texts, "PROCESSED_DIR", processed)
    monkeypatch.setattr(summarizer, "PROCESSED_DIR", processed)
    monkeypatch.setattr(summarizer, "SUMMARIES_PATH", summaries_path)
    monkeypatch.setattr(run_phase3, "DEV_SUMMARIES_JSONL_DIR", dev_dir)
    monkeypatch.setattr(summarizer, "LOGS_DIR", tmp_path / "logs")
    return manifest_path, summaries_path, dev_dir, dois_by_journal


def _run_dev_summarize(manifest_path: Path, extra: list[str] | None = None) -> int:
    """In plain English: pretends to type
    `python llm-sum/run_phase3.py summarize --mode dev --manifest ... --providers openai --force`
    (plus any `extra` flags), through the real argparse parser, and runs it."""
    import run_phase3

    parser = run_phase3.build_parser()
    args = parser.parse_args(
        ["summarize", "--mode", "dev", "--manifest", str(manifest_path),
         "--providers", "openai", "--force"] + (extra or [])
    )
    return run_phase3.cmd_summarize(args)


# In plain English: confirms that `summarize --mode dev` correctly skips
# papers that were already summarized in an earlier dev run — here, one
# whole journal (javma) is already "done", so a re-run should only pick
# papers from the remaining journal (jvim).
def test_cmd_summarize_dev_skips_dois_already_in_dev_folder(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Papers already written to data/dev_summaries_jsonl/ are excluded from the
    dev-mode random pick, so a re-run picks from the remainder."""
    manifest_path, summaries_path, dev_dir, dois_by_journal = _setup_dev_summarize(
        tmp_path, monkeypatch
    )
    # All javma papers already summarised in a prior dev run.
    for doi in dois_by_journal["javma"]:
        _write_dev_readable_txt(dev_dir, doi)

    assert _run_dev_summarize(manifest_path) == 0

    rows = [json.loads(l) for l in summaries_path.read_text(encoding="utf-8").splitlines()]
    # javma is fully excluded; only jvim papers can be picked.
    assert rows, "expected at least one summarised paper"
    assert {row["journal"] for row in rows} == {"jvim"}
    assert all(not row["doi"].startswith("10.9999/javma") for row in rows)


# In plain English: confirms the opposite of the test above — passing
# --no-skip-existing makes dev mode reconsider ALL journals, including the
# one that already has papers in the dev folder.
def test_cmd_summarize_dev_no_skip_existing_reconsiders(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--no-skip-existing ignores the dev folder and picks one per journal again."""
    manifest_path, summaries_path, dev_dir, dois_by_journal = _setup_dev_summarize(
        tmp_path, monkeypatch
    )
    for doi in dois_by_journal["javma"]:
        _write_dev_readable_txt(dev_dir, doi)

    assert _run_dev_summarize(manifest_path, ["--no-skip-existing"]) == 0

    rows = [json.loads(l) for l in summaries_path.read_text(encoding="utf-8").splitlines()]
    # With skipping disabled, both journals are eligible again.
    assert {row["journal"] for row in rows} == {"jvim", "javma"}


# In plain English: confirms --output-subdir redirects the readable output
# into data/dev_summaries_jsonl/<name>/ instead of the top level, and that
# the subfolder tracks its OWN incremental "already done" pool — a paper
# already summarized straight into the parent dev folder is still eligible
# to be re-picked and written into the subfolder.
def test_cmd_summarize_dev_output_subdir_redirects_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """--output-subdir writes into a subfolder with its own independent
    skip-existing pool, leaving the parent dev folder untouched."""
    manifest_path, summaries_path, dev_dir, dois_by_journal = _setup_dev_summarize(
        tmp_path, monkeypatch
    )
    # All javma papers already summarised directly in the parent dev folder.
    for doi in dois_by_journal["javma"]:
        _write_dev_readable_txt(dev_dir, doi)

    assert _run_dev_summarize(manifest_path, ["--output-subdir", "mod_summaries"]) == 0

    # New output lands in the subfolder, not the parent.
    mod_dir = dev_dir / "mod_summaries"
    assert list(mod_dir.glob("*.txt")), "expected readable files in mod_summaries/"
    # The parent still holds only the 3 pre-seeded javma files — nothing new
    # was written there by this run.
    assert len(list(dev_dir.glob("*.txt"))) == 3

    rows = [json.loads(l) for l in summaries_path.read_text(encoding="utf-8").splitlines()]
    # javma papers already "done" in the PARENT folder are still eligible
    # here, since mod_summaries/ tracks its own independent pool.
    assert {row["journal"] for row in rows} == {"jvim", "javma"}


# ---------------------------------------------------------------------------
# summarize --mode single: readable output into data/single_summaries_jsonl/
# ---------------------------------------------------------------------------

def _setup_single_summarize(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, dois: list[str],
):
    """Shared wiring for the single-mode summarize tests. Returns paths.

    In plain English: sets up a fake manifest (with however many DOIs the
    test passes in) pointed at scratch folders, mirroring
    ``_setup_dev_summarize`` above but for `summarize --mode single`.
    """
    import prepare_texts
    import run_phase3
    import summarizer
    from file_paths import doi_to_slug

    monkeypatch.setenv("DRY_RUN", "true")
    monkeypatch.setattr(summarizer, "DRY_RUN", True)

    manifest_path = tmp_path / "manifest.jsonl"
    processed = tmp_path / "processed"
    processed.mkdir()
    summaries_path = tmp_path / "summaries.jsonl"
    single_dir = tmp_path / "single_summaries_jsonl"

    with open(manifest_path, "w", encoding="utf-8") as f:
        for doi in dois:
            f.write(json.dumps({"doi": doi, "journal": "jvim", "title": f"Paper {doi}"}) + "\n")
            slug = doi_to_slug(doi)
            (processed / f"{slug}.jsonl").write_text(
                json.dumps({"doi": doi, "slug": slug, "text": "Body text. " * 30}) + "\n",
                encoding="utf-8",
            )

    monkeypatch.setattr(run_phase3, "PROCESSED_DIR", processed)
    monkeypatch.setattr(prepare_texts, "PROCESSED_DIR", processed)
    monkeypatch.setattr(summarizer, "PROCESSED_DIR", processed)
    monkeypatch.setattr(summarizer, "SUMMARIES_PATH", summaries_path)
    monkeypatch.setattr(run_phase3, "SINGLE_SUMMARIES_JSONL_DIR", single_dir)
    monkeypatch.setattr(summarizer, "LOGS_DIR", tmp_path / "logs")
    return manifest_path, summaries_path, single_dir


def _run_single_summarize(manifest_path: Path, extra: list[str] | None = None) -> int:
    """In plain English: pretends to type
    `python llm-sum/run_phase3.py summarize --mode single --manifest ... --providers openai --force`
    (plus any `extra` flags), through the real argparse parser, and runs it."""
    import run_phase3

    parser = run_phase3.build_parser()
    args = parser.parse_args(
        ["summarize", "--mode", "single", "--manifest", str(manifest_path),
         "--providers", "openai", "--force"] + (extra or [])
    )
    return run_phase3.cmd_summarize(args)


def test_cmd_summarize_single_writes_readable_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """`summarize --mode single` writes exactly one readable .txt into
    data/single_summaries_jsonl/, for the one paper it actually summarized.

    In plain English: single mode's paper_limit is 1, so out of two
    manifest papers only the first should get summarized -- and only that
    one should show up in the readable single-summaries folder.
    """
    dois = ["10.9999/single.0001", "10.9999/single.0002"]
    manifest_path, summaries_path, single_dir = _setup_single_summarize(
        tmp_path, monkeypatch, dois
    )

    assert _run_single_summarize(manifest_path) == 0

    rows = [json.loads(l) for l in summaries_path.read_text(encoding="utf-8").splitlines()]
    assert {row["doi"] for row in rows} == {dois[0]}

    txt_files = list(single_dir.glob("*.txt"))
    assert len(txt_files) == 1
    text = txt_files[0].read_text(encoding="utf-8")
    assert text.startswith(f"DOI: {dois[0]}")
    assert "summarize --mode single" in text
    assert dois[1] not in text

    # Prose sibling under prose/, with the word-count header; bullet file above
    # stays at the top level for the discovery readers.
    prose_files = list((single_dir / "prose").glob("*.txt"))
    assert len(prose_files) == 1
    prose_text = prose_files[0].read_text(encoding="utf-8")
    assert prose_text.startswith(f"DOI: {dois[0]}")
    assert "Summary (prose):" in prose_text


def test_cmd_summarize_single_no_new_paper_writes_nothing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A single-mode run over an empty manifest touches no paper, so nothing
    is written to data/single_summaries_jsonl/ (no empty/junk files)."""
    manifest_path, _summaries_path, single_dir = _setup_single_summarize(
        tmp_path, monkeypatch, []
    )

    assert _run_single_summarize(manifest_path) == 0
    assert not single_dir.exists() or not list(single_dir.glob("*.txt"))


# In plain English: checks the safety net for crashes — if something goes
# wrong partway through evaluation (simulated here by making run_evaluation
# deliberately raise an error), the run manifest should still end up marked
# "failed" with a finish time recorded, rather than being left in a
# permanently ambiguous "started" state. The original crash/error is still
# allowed to propagate (pytest.raises below) — this only checks the
# record-keeping around it.
def test_evaluate_marks_manifest_failed_on_exception(_wired_paths, monkeypatch: pytest.MonkeyPatch) -> None:
    dois = ["10.9999/manifest.0003"]
    _write_fake_summaries(_wired_paths["summaries_path"], _wired_paths["processed_dir"], dois)

    import evaluator

    def _boom(**kwargs):
        raise RuntimeError("simulated crash mid-evaluation")

    monkeypatch.setattr(evaluator, "run_evaluation", _boom)

    with pytest.raises(RuntimeError, match="simulated crash"):
        _run_evaluate(["evaluate", "--mode", "test"])

    manifest_path = _find_manifest(_wired_paths["manifest_dir"])
    data = json.loads(manifest_path.read_text(encoding="utf-8"))

    assert data["status"] == "failed"
    assert data["finished_utc"] is not None


# ---------------------------------------------------------------------------
# export-human-review CLI wiring
# ---------------------------------------------------------------------------
# In plain English: checks only the WIRING for the real export subcommand --
# that it exposes --sample-size/--overlap-ratio/--seed (no --reviewers, no
# --sample-unit; each run now writes ONE MORE humanN/ folder) and forwards
# them unchanged to human_review.main() -- not the export logic itself,
# which tests/test_human_review.py already covers in full.

def test_export_human_review_parser_accepts_flags() -> None:
    """The subcommand parses its flags and dispatches to the right handler."""
    import run_phase3

    parser = run_phase3.build_parser()
    args = parser.parse_args([
        "export-human-review", "--mode", "test",
        "--sample-size", "10", "--overlap-ratio", "0.4", "--seed", "7",
    ])
    assert args.func is run_phase3.cmd_export_human_review
    assert args.sample_size == 10
    assert args.overlap_ratio == 0.4
    assert args.seed == 7


def test_cmd_export_human_review_forwards_flags(monkeypatch: pytest.MonkeyPatch) -> None:
    """cmd_export_human_review forwards every set flag to human_review.main."""
    import run_phase3

    captured: dict = {}

    def _fake_main(argv):
        captured["argv"] = argv
        return 0

    import human_review
    monkeypatch.setattr(human_review, "main", _fake_main)

    parser = run_phase3.build_parser()
    args = parser.parse_args([
        "export-human-review", "--mode", "test",
        "--sample-size", "10", "--overlap-ratio", "0.4", "--seed", "7",
    ])
    result = args.func(args)

    assert result == 0
    assert captured["argv"] == [
        "--sample-size", "10", "--overlap-ratio", "0.4", "--seed", "7",
    ]


def test_cmd_export_human_review_omits_unset_flags(monkeypatch: pytest.MonkeyPatch) -> None:
    """Flags left unset on the CLI are not forwarded, so human_review's own
    .env/default fallback chain (see its --help) still applies."""
    import run_phase3

    captured: dict = {}

    def _fake_main(argv):
        captured["argv"] = argv
        return 0

    import human_review
    monkeypatch.setattr(human_review, "main", _fake_main)

    parser = run_phase3.build_parser()
    args = parser.parse_args(["export-human-review", "--mode", "test"])
    result = args.func(args)

    assert result == 0
    assert captured["argv"] == []


# ---------------------------------------------------------------------------
# export-pilot-human-review CLI wiring
# ---------------------------------------------------------------------------
# In plain English: pilot_human_review.py works as a standalone script, but
# is also meant to be runnable as `python llm-sum/run_phase3.py
# export-pilot-human-review ...`, mirroring export-human-review. These tests
# check only the WIRING -- that the subcommand exists with the right flags
# and that run_phase3.cmd_export_pilot_human_review forwards them to
# pilot_human_review.main() unchanged -- not the export logic itself, which
# tests/test_pilot_human_review.py already covers in full.

def test_export_pilot_human_review_parser_accepts_flags() -> None:
    """The subcommand parses its flags and dispatches to the right handler."""
    import run_phase3

    parser = run_phase3.build_parser()
    args = parser.parse_args([
        "export-pilot-human-review", "--mode", "test",
        "--sample-size", "5", "--overlap-ratio", "0.4", "--seed", "7",
    ])
    assert args.func is run_phase3.cmd_export_pilot_human_review
    assert args.sample_size == 5
    assert args.overlap_ratio == 0.4
    assert args.seed == 7


def test_cmd_export_pilot_human_review_forwards_flags(monkeypatch: pytest.MonkeyPatch) -> None:
    """cmd_export_pilot_human_review forwards every set flag to pilot_human_review.main."""
    import run_phase3

    captured: dict = {}

    def _fake_main(argv):
        captured["argv"] = argv
        return 0

    import pilot_human_review
    monkeypatch.setattr(pilot_human_review, "main", _fake_main)

    parser = run_phase3.build_parser()
    args = parser.parse_args([
        "export-pilot-human-review", "--mode", "test",
        "--sample-size", "5", "--overlap-ratio", "0.4", "--seed", "7",
    ])
    result = args.func(args)

    assert result == 0
    assert captured["argv"] == [
        "--sample-size", "5", "--overlap-ratio", "0.4", "--seed", "7",
    ]


def test_cmd_export_pilot_human_review_omits_unset_flags(monkeypatch: pytest.MonkeyPatch) -> None:
    """Flags left unset on the CLI are not forwarded, so pilot_human_review's
    own .env/default fallback chain (see its --help) still applies."""
    import run_phase3

    captured: dict = {}

    def _fake_main(argv):
        captured["argv"] = argv
        return 0

    import pilot_human_review
    monkeypatch.setattr(pilot_human_review, "main", _fake_main)

    parser = run_phase3.build_parser()
    args = parser.parse_args(["export-pilot-human-review", "--mode", "test"])
    result = args.func(args)

    assert result == 0
    assert captured["argv"] == []
