"""
src/scenarios/corpus_status.py - Primary research corpus scenario

WHY THIS MODULE EXISTS
----------------------
The current pipeline scoreboard is a reproducible scenario: five target
veterinary journals, primary-research PDFs counted toward quota, and secondary
review PDFs retained but excluded from quota. Keeping this policy here lets
pipeline.py focus on orchestration and printing.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Callable, Iterable

from collect import JOURNAL_TARGETS
from file_paths import pdf_path_candidates
from scenarios.base import Scenario, ScenarioPaths


ErrorLogger = Callable[[str, str, str], None]


@dataclass(frozen=True)
class CorpusStatusReport:
    """Pure report data for tests; pipeline.py remains responsible for printing."""

    records: list[dict[str, Any]]
    downloaded: list[str]
    downloaded_primary: list[str]
    downloaded_secondary: list[str]
    missing_pdfs: list[str]
    oa_count: int
    manual_count: int
    n_primary: int
    n_secondary: int
    n_total: int
    total_missing: int
    journal_counts: dict[str, dict[str, Any]]


def _noop_error_logger(doi: str, stage: str, message: str) -> None:
    """Default logger for tests that do not need error-log side effects."""
    return None


def iter_jsonl_records(
    path: Path,
    *,
    stage: str,
    error_logger: ErrorLogger = _noop_error_logger,
) -> Iterable[tuple[int, dict[str, Any]]]:
    """Yield valid JSON objects from JSONL while skipping malformed lines.

    JSONL is used throughout this project because append-only files can survive
    interrupted runs. Skipping bad rows here matches the existing pipeline
    behavior while making the parsing rule independently testable.
    """
    if not path.exists():
        return

    with open(path, encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                error_logger("N/A", "pipeline", f"Malformed {stage} manifest line {line_num}")
                continue
            if isinstance(record, dict):
                yield line_num, record


def load_manifest_records(
    scenario: "PrimaryResearchCorpusScenario",
    *,
    error_logger: ErrorLogger = _noop_error_logger,
) -> dict[str, Any]:
    """Load OA and manual manifests into a deduplicated corpus seed.

    OA rows are loaded first because they are generated by the pipeline and have
    more consistent metadata. Manual rows fill gaps only after their PDF is
    confirmed on disk so the corpus count is not inflated by hand-entered rows.
    """
    records: list[dict[str, Any]] = []
    seen_dois: set[str] = set()
    oa_count = 0

    if scenario.paths.manifest_path.exists():
        for _line_num, record in iter_jsonl_records(
            scenario.paths.manifest_path,
            stage="OA",
            error_logger=error_logger,
        ):
            doi = str(record.get("doi", "")).strip()
            if doi and doi not in seen_dois:
                seen_dois.add(doi)
                record["_source"] = "oa"
                records.append(record)
                oa_count += 1
    else:
        print(f"[pipeline] OA manifest not found at {scenario.paths.manifest_path}. Run collect.py first.")

    manual_count = 0
    invalid_manual: list[dict[str, str]] = []

    if scenario.paths.manual_manifest_path.exists():
        for line_num, record in iter_jsonl_records(
            scenario.paths.manual_manifest_path,
            stage="manual",
            error_logger=error_logger,
        ):
            doi = str(record.get("doi", "")).strip()
            if not doi:
                error_logger("N/A", "pipeline", f"Manual manifest line {line_num}: missing doi")
                continue

            if doi in seen_dois:
                continue

            pdf_path = scenario.pdf_path_for(record)
            if pdf_path is None:
                invalid_manual.append({
                    "doi": doi,
                    "title": str(record.get("title", "")),
                    "reason": "PDF not found in data/raw/",
                })
                continue

            seen_dois.add(doi)
            record["_source"] = "manual"
            records.append(record)
            manual_count += 1

    return {
        "records": records,
        "oa_count": oa_count,
        "manual_count": manual_count,
        "invalid_manual": invalid_manual,
    }


class PrimaryResearchCorpusScenario(Scenario):
    """Current Phase 2/4 corpus health scenario used by pipeline.py."""

    name = "primary_research_corpus"
    description = "Balanced 2023-2026 veterinary primary-research corpus."
    journal_targets = JOURNAL_TARGETS
    oa_threshold = 200

    def records(self) -> Iterable[dict[str, Any]]:
        """Yield deduplicated OA and valid manual manifest records."""
        seed = load_manifest_records(self)
        yield from seed["records"]

    @property
    def corpus_target(self) -> int:
        """Total primary-paper quota across the configured target journals."""
        return sum(self.journal_targets.values())

    def is_secondary_pdf(self, pdf_name: str) -> bool:
        """The existing project convention tags secondary reviews with '2_'."""
        return pdf_name.startswith("2_")

    def pdf_path_for(self, record: dict[str, Any]) -> Path | None:
        """Use shared filename candidates, plus the local secondary prefix rule.

        The shared helper intentionally owns normal legacy/descriptive naming.
        This scenario adds only the documented ``2_`` variant so status reporting
        can count secondary review PDFs without changing downloader path logic.
        """
        candidates = pdf_path_candidates(self.paths.raw_dir, record)
        for candidate in candidates:
            if candidate.exists():
                return candidate
            secondary_candidate = candidate.with_name(f"2_{candidate.name}")
            if secondary_candidate.exists():
                return secondary_candidate
        return None

    def counts_toward_quota(self, record: dict[str, Any]) -> bool:
        """Primary papers count; secondary review PDFs remain reference material."""
        pdf_path = self.pdf_path_for(record)
        return pdf_path is not None and not self.is_secondary_pdf(pdf_path.name)

    def classify_record_pdf(self, record: dict[str, Any]) -> tuple[str, Path | None]:
        """Return missing, primary, or secondary for a manifest record's PDF."""
        pdf_path = self.pdf_path_for(record)
        if pdf_path is None:
            return "missing", None
        if self.is_secondary_pdf(pdf_path.name):
            return "secondary", pdf_path
        return "primary", pdf_path

    def build_status_report(self, corpus: dict[str, Any]) -> CorpusStatusReport:
        """Build corpus status data separately from stdout formatting.

        The report contains only deterministic counts derived from manifests and
        files. Keeping this pure makes the policy easy to test before the CLI
        prints the familiar researcher-facing scoreboard.
        """
        records = list(corpus["records"])
        downloaded: list[str] = []
        downloaded_primary: list[str] = []
        downloaded_secondary: list[str] = []
        missing_pdfs: list[str] = []
        journal_counts: dict[str, dict[str, Any]] = {}

        for record in records:
            doi = str(record.get("doi", "")).strip()
            journal = str(record.get("journal", "Unknown") or "Unknown")
            journal_counts.setdefault(journal, {"primary": 0, "secondary": 0, "source": set()})
            classification, pdf_path = self.classify_record_pdf(record)

            if classification == "missing":
                missing_pdfs.append(doi)
            else:
                downloaded.append(doi)
                if classification == "secondary":
                    downloaded_secondary.append(doi)
                    journal_counts[journal]["secondary"] += 1
                else:
                    downloaded_primary.append(doi)
                    journal_counts[journal]["primary"] += 1

            journal_counts[journal]["source"].add(record.get("_source", "oa"))

        n_primary = len(downloaded_primary)
        n_secondary = len(downloaded_secondary)
        n_total = len(downloaded)
        total_missing = max(0, self.corpus_target - n_primary)

        return CorpusStatusReport(
            records=records,
            downloaded=downloaded,
            downloaded_primary=downloaded_primary,
            downloaded_secondary=downloaded_secondary,
            missing_pdfs=missing_pdfs,
            oa_count=int(corpus["oa_count"]),
            manual_count=int(corpus["manual_count"]),
            n_primary=n_primary,
            n_secondary=n_secondary,
            n_total=n_total,
            total_missing=total_missing,
            journal_counts=journal_counts,
        )

    def load_corpus(self, *, error_logger: ErrorLogger = _noop_error_logger) -> dict[str, Any]:
        """Return the pipeline-compatible corpus dictionary for this scenario."""
        corpus = load_manifest_records(self, error_logger=error_logger)
        report = self.build_status_report(corpus)
        corpus.update({
            "downloaded": report.downloaded,
            "downloaded_primary": report.downloaded_primary,
            "downloaded_secondary": report.downloaded_secondary,
            "missing_pdfs": report.missing_pdfs,
        })
        return corpus

    def metadata(self) -> dict[str, Any]:
        data = super().metadata()
        data.update({
            "journal_targets": dict(self.journal_targets),
            "oa_threshold": self.oa_threshold,
            "corpus_target": self.corpus_target,
        })
        return data
