"""
scripts/verify_extraction.py — audit raw vs cleaned text per paper
====================================================================

For every PDF in ``data/raw/``:

1. Extract the RAW pdfplumber text (no cleaning at all).
2. Read the matching ``data/processed/*.jsonl`` cache (descriptive name
   first, legacy ``{slug}.jsonl`` as fallback).
3. Compare word counts.

Why this exists
---------------
A PDF can pass Phase 2's validation gate (real PDF, enough pages, has
section headers) and still get butchered by Phase 3 extraction — for
example, when ``remove_references_section`` matches a "References" word
in the discussion text and eats the second half of the paper.
``prepare_texts.py`` already prints a warning when the cleaned count
drops below ``MIN_WORD_COUNT_WARN``, but the warning scrolls past
during a 250-paper run. This script gives a one-shot, sortable audit
table.

No API calls. Safe to re-run.

Thresholds
----------
``ratio = cleaned_words / raw_words``. Healthy papers land at 0.70-0.90
because references + publisher noise are intentionally removed.

  PASS  : ratio >= 0.50 AND cleaned_words >= 3000
  WARN  : ratio 0.30-0.49, OR cleaned_words 1500-2999
  FAIL  : ratio < 0.30, OR cleaned_words < 1500, OR missing cache,
          OR raw_words < 500 (image-only or unreadable PDF)

The 90% suggestion DeepSeek/Gemini floated would flag every paper —
reference stripping legitimately removes 15-25% of a research article.
0.50 is a conservative lower bound for "the body survived cleaning."

Exit code: 0 if zero FAILs; 1 if any FAIL (regardless of WARN count).

Usage
-----
    python scripts/verify_extraction.py                # full audit
    python scripts/verify_extraction.py --limit 5      # spot-check
    python scripts/verify_extraction.py --quiet        # only WARN/FAIL
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Repo layout: scripts/ is a sibling of src/ and llm-sum/. Both must be
# on sys.path because we reuse src/extract.py + src/file_paths.py and
# llm-sum/prepare_texts.py's path-resolution helper.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT / "llm-sum"))

import pdfplumber  # noqa: E402
from file_paths import descriptive_stem, doi_to_slug  # noqa: E402

DATA_DIR = REPO_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
MANIFEST_PATH = DATA_DIR / "manifest.jsonl"
REPORT_PATH = DATA_DIR / "verify_extraction_report.txt"

# Thresholds — see module docstring.
RATIO_PASS = 0.50
RATIO_WARN = 0.30
CLEANED_PASS_WORDS = 3000
CLEANED_WARN_WORDS = 1500
RAW_MIN_WORDS = 500


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def _iter_manifest(path: Path):
    if not path.exists():
        return
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def _build_pdf_to_record(manifest_path: Path) -> dict[str, dict]:
    """
    Map the PDF stem we'd expect on disk to its manifest record. We try
    both the descriptive stem AND the legacy ``doi_to_slug`` slug so both
    naming conventions resolve back to the record (and hence the right
    cleaned-text cache).
    """
    out: dict[str, dict] = {}
    for record in _iter_manifest(manifest_path):
        doi = str(record.get("doi", "")).strip()
        if not doi:
            continue
        if record.get("journal") and record.get("title"):
            out[descriptive_stem(record)] = record
        out[doi_to_slug(doi)] = record
    return out


def _find_cleaned_cache(pdf_stem: str, record: dict | None) -> Path | None:
    """
    Find the data/processed/*.jsonl for this PDF.

    Order: descriptive name (new) → legacy slug name. Returns None if
    no matching cache file exists.
    """
    if record and record.get("journal") and record.get("title"):
        candidate = PROCESSED_DIR / f"{descriptive_stem(record)}.jsonl"
        if candidate.exists():
            return candidate

    # Fallback: descriptive name might exist while record lookup failed
    # (rare), or only the legacy name was generated by the old code.
    descriptive = PROCESSED_DIR / f"{pdf_stem}.jsonl"
    if descriptive.exists():
        return descriptive

    if record:
        doi = str(record.get("doi", "")).strip()
        if doi:
            legacy = PROCESSED_DIR / f"{doi_to_slug(doi)}.jsonl"
            if legacy.exists():
                return legacy

    # Last try: legacy slug derived from the PDF filename itself.
    parts = pdf_stem.split("__")
    candidate_slug = parts[-1] if len(parts) > 1 else pdf_stem
    candidate = PROCESSED_DIR / f"{candidate_slug}.jsonl"
    return candidate if candidate.exists() else None


def _read_cleaned_counts(jsonl_path: Path) -> tuple[int, int] | None:
    """Return ``(word_count, char_count)`` from the cache, or None on failure."""
    try:
        line = jsonl_path.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    if not line:
        return None
    try:
        obj = json.loads(line)
    except json.JSONDecodeError:
        return None
    if not isinstance(obj, dict):
        return None
    text = obj.get("text") or ""
    word_count = obj.get("word_count")
    if not isinstance(word_count, int):
        word_count = len(str(text).split())
    char_count = obj.get("char_count")
    if not isinstance(char_count, int):
        char_count = len(str(text))
    return word_count, char_count


def _raw_pdf_stats(pdf_path: Path) -> tuple[int, int] | None:
    """
    Return ``(page_count, raw_word_count)`` from an unfiltered pdfplumber pass.
    """
    try:
        with pdfplumber.open(pdf_path) as pdf:
            pages = len(pdf.pages)
            chunks: list[str] = []
            for page in pdf.pages:
                chunk = page.extract_text() or ""
                chunks.append(chunk)
            raw_text = "\n".join(chunks)
    except Exception:
        return None
    return pages, len(raw_text.split())


# ---------------------------------------------------------------------------
# Classification
# ---------------------------------------------------------------------------

def classify(*, raw_words: int, cleaned_words: int, jsonl_exists: bool) -> tuple[str, str]:
    """Return ``(status, note)`` for one paper."""
    if not jsonl_exists:
        return "FAIL", "no cache (prepare_texts has not run for this PDF)"
    if raw_words < RAW_MIN_WORDS:
        return "FAIL", f"raw words {raw_words} < {RAW_MIN_WORDS} (image-only PDF?)"
    if cleaned_words < CLEANED_WARN_WORDS:
        return "FAIL", f"cleaned words {cleaned_words} < {CLEANED_WARN_WORDS}"

    ratio = cleaned_words / raw_words if raw_words else 0.0
    if ratio < RATIO_WARN:
        return "FAIL", f"ratio {ratio:.2f} < {RATIO_WARN} (cleaning ate the body?)"
    if ratio < RATIO_PASS or cleaned_words < CLEANED_PASS_WORDS:
        return "WARN", f"ratio {ratio:.2f}, cleaned {cleaned_words} words"
    return "PASS", ""


# ---------------------------------------------------------------------------
# Run loop
# ---------------------------------------------------------------------------

def run(*, limit: int | None, quiet: bool) -> int:
    if not RAW_DIR.exists():
        print(f"[verify] {RAW_DIR} does not exist; nothing to audit.")
        return 0

    pdf_paths = sorted(RAW_DIR.glob("*.pdf"))
    if limit is not None:
        pdf_paths = pdf_paths[:limit]
    if not pdf_paths:
        print(f"[verify] No PDFs found under {RAW_DIR}.")
        return 0

    pdf_to_record = _build_pdf_to_record(MANIFEST_PATH)

    header = f"{'PDF filename':<60}  {'pages':>5}  {'raw':>7}  {'clean':>7}  {'ratio':>5}  {'status':<5}"
    print(header)
    print("-" * len(header))

    counts = {"PASS": 0, "WARN": 0, "FAIL": 0}
    report_lines: list[str] = [header, "-" * len(header)]

    for pdf_path in pdf_paths:
        pdf_stem = pdf_path.stem
        # Match by descriptive stem first, fall back to legacy slug at end.
        record = pdf_to_record.get(pdf_stem)
        if record is None:
            # Legacy name with no __ separators is itself a doi_to_slug result.
            record = pdf_to_record.get(pdf_stem)

        raw_stats = _raw_pdf_stats(pdf_path)
        if raw_stats is None:
            line = f"{pdf_path.name[:60]:<60}  {'?':>5}  {'?':>7}  {'?':>7}  {'?':>5}  FAIL   (pdfplumber could not open)"
            print(line)
            report_lines.append(line)
            counts["FAIL"] += 1
            continue
        pages, raw_words = raw_stats

        cache_path = _find_cleaned_cache(pdf_stem, record)
        if cache_path is None:
            cleaned_words = 0
            jsonl_exists = False
        else:
            stats = _read_cleaned_counts(cache_path)
            cleaned_words = stats[0] if stats else 0
            jsonl_exists = stats is not None and cleaned_words > 0

        status, note = classify(
            raw_words=raw_words, cleaned_words=cleaned_words, jsonl_exists=jsonl_exists,
        )
        counts[status] += 1

        ratio = cleaned_words / raw_words if raw_words else 0.0
        line = (f"{pdf_path.name[:60]:<60}  {pages:>5}  {raw_words:>7}  "
                f"{cleaned_words:>7}  {ratio:>5.2f}  {status:<5}")
        if note:
            line += f"  ({note})"

        if not quiet or status != "PASS":
            print(line)
        report_lines.append(line)

    summary = (f"\nSummary: PASS={counts['PASS']}  WARN={counts['WARN']}  "
               f"FAIL={counts['FAIL']}  (total {sum(counts.values())})")
    print(summary)
    report_lines.append(summary)

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(report_lines) + "\n", encoding="utf-8")
    print(f"\nReport written to {REPORT_PATH}")

    return 1 if counts["FAIL"] > 0 else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Compare raw PDF text against cleaned cache (no API calls)."
    )
    parser.add_argument("--limit", type=int, default=None,
                        help="Audit only the first N PDFs (handy for spot-checks).")
    parser.add_argument("--quiet", action="store_true",
                        help="Only print WARN/FAIL rows; PASS rows still go to the report file.")
    args = parser.parse_args(argv)
    return run(limit=args.limit, quiet=args.quiet)


if __name__ == "__main__":
    sys.exit(main())
